/**
 * Supply-chain tools: the workflow the plan names for Phase 9,
 * `check_inventory -> compute_reorder_qty -> validate_compliance -> notify_supplier`,
 * plus a supplier lookup that runs in parallel and a manual-review queue the
 * replanner can route to when a supplier cannot be reached.
 *
 * These are real tools, not stubs. Each reads the dataset, does real work, and
 * returns MCP `structuredContent` that the next task consumes. The only side
 * effect is writing files to a local outbox — nothing is emailed or sent — so
 * the demo can show a purchase order on disk without doing anything a
 * reviewer would have to undo.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { z } from "zod";

import { errorResult, textResult, type ToolDefinition } from "../../mcp/tool-types.js";

import {
  computeReorderLines,
  DEFAULT_WAREHOUSE_PATH,
  findLowStock,
  groupBySupplier,
  loadWarehouse,
  validateCompliance,
  type Breach,
  type LowStockItem,
  type ReorderLine,
  type Supplier,
  type Warehouse,
} from "./warehouse.js";

export const DEFAULT_OUTBOX_DIR = join(process.cwd(), "demo", "outbox");

export interface SupplyChainToolOptions {
  /** Called on every invocation, so edits to the dataset are picked up without a restart. */
  loadWarehouse?: () => Warehouse;
  outboxDir?: string;
  now?: () => Date;
  /** Supplier ids whose ordering portal should be treated as down, whatever the dataset says. */
  portalDown?: readonly string[];
}

/**
 * Arguments every supply-chain tool accepts from the runtime. `upstream` maps
 * each direct dependency's task id to its structured output; `runId` names the
 * outbox folder so each run's documents stay separate.
 */
const runtimeArgs = {
  upstream: z.record(z.unknown()).optional(),
  runId: z.string().optional(),
};

type Upstream = Record<string, unknown> | undefined;

/** The first direct dependency whose output is of the given kind. */
export function findUpstream<T>(upstream: Upstream, kind: string): T | undefined {
  for (const value of Object.values(upstream ?? {})) {
    if (typeof value === "object" && value !== null && (value as { kind?: unknown }).kind === kind) {
      return value as T;
    }
  }
  return undefined;
}

const missingUpstream = (tool: string, kind: string, producer: string) =>
  errorResult(
    `${tool} needs ${kind} data from an upstream ${producer} task, and none was provided. ` +
      `This task must list that task in dependsOn.`,
  );

const usd = (value: number) =>
  `$${value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export interface InventoryOutput {
  kind: "inventory";
  warehouse: string;
  asOf: string;
  reviewPeriodDays: number;
  checked: number;
  lowStock: LowStockItem[];
}

export interface SuppliersOutput {
  kind: "suppliers";
  suppliers: Supplier[];
}

export interface ReorderOutput {
  kind: "reorder";
  reviewPeriodDays: number;
  lines: ReorderLine[];
  totalValueUsd: number;
}

export interface ComplianceOutput {
  kind: "compliance";
  approved: ReorderLine[];
  breaches: Breach[];
  approvedValueUsd: number;
  supplierSource: "upstream" | "master data";
}

export interface PurchaseOrder {
  supplierId: string;
  supplierName: string;
  email: string;
  lines: ReorderLine[];
  valueUsd: number;
  file: string;
}

export interface NotificationOutput {
  kind: "notification";
  orders: PurchaseOrder[];
}

export interface ManualReviewOutput {
  kind: "manual_review";
  file: string;
  lines: ReorderLine[];
  breaches: Breach[];
  reason: string;
}

function renderPurchaseOrder(
  warehouse: Warehouse,
  supplier: Supplier,
  lines: readonly ReorderLine[],
  issuedAt: Date,
): string {
  const total = lines.reduce((sum, line) => sum + line.lineValueUsd, 0);
  return [
    `# Purchase order - ${supplier.name}`,
    "",
    `- **To:** ${supplier.email}`,
    `- **From:** ${warehouse.warehouse}`,
    `- **Issued:** ${issuedAt.toISOString()}`,
    "",
    "| SKU | Item | Qty | Unit | Line value |",
    "|---|---|---:|---:|---:|",
    ...lines.map(
      (line) =>
        `| ${line.sku} | ${line.name} | ${line.qty} | ${usd(line.unitCostUsd)} | ${usd(line.lineValueUsd)} |`,
    ),
    "",
    `**Total: ${usd(total)}**`,
    "",
    "_Generated by the MCP-X demo. Written to a local outbox only; nothing was transmitted._",
    "",
  ].join("\n");
}

export function makeSupplyChainTools(
  options: SupplyChainToolOptions = {},
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
): ToolDefinition<any>[] {
  const load =
    options.loadWarehouse ?? (() => loadWarehouse(process.env["WAREHOUSE_PATH"] ?? DEFAULT_WAREHOUSE_PATH));
  const outboxDir = options.outboxDir ?? process.env["OUTBOX_DIR"] ?? DEFAULT_OUTBOX_DIR;
  const now = options.now ?? (() => new Date());
  const forcedDown = new Set(options.portalDown ?? []);

  const runFolder = (runId: string | undefined) => {
    const dir = join(outboxDir, runId ?? "adhoc");
    mkdirSync(dir, { recursive: true });
    return dir;
  };

  const checkInventory: ToolDefinition<typeof runtimeArgs> = {
    name: "check_inventory",
    description:
      "Reads current warehouse stock and returns every SKU whose inventory position (on hand + on order) is at or below its reorder point.",
    capability: "research",
    produces: "inventory",
    schema: runtimeArgs,
    handler: () => {
      const warehouse = load();
      const lowStock = findLowStock(warehouse);
      const output: InventoryOutput = {
        kind: "inventory",
        warehouse: warehouse.warehouse,
        asOf: warehouse.asOf,
        reviewPeriodDays: warehouse.reviewPeriodDays,
        checked: warehouse.skus.length,
        lowStock,
      };
      return textResult(
        `${lowStock.length} of ${warehouse.skus.length} SKUs at or below reorder point: ${
          lowStock.map((item) => item.sku).join(", ") || "none"
        }`,
        output as unknown as Record<string, unknown>,
      );
    },
  };

  const lookupSuppliers: ToolDefinition<typeof runtimeArgs> = {
    name: "lookup_suppliers",
    description:
      "Looks up supplier master records (status, certifications, contact) for the suppliers of the low-stock SKUs. Consumes check_inventory output.",
    capability: "research",
    produces: "suppliers",
    consumes: ["inventory"],
    schema: runtimeArgs,
    handler: ({ upstream }) => {
      const inventory = findUpstream<InventoryOutput>(upstream, "inventory");
      if (!inventory) return missingUpstream("lookup_suppliers", "inventory", "check_inventory");

      const needed = new Set(inventory.lowStock.map((item) => item.supplierId));
      const suppliers = load().suppliers.filter((supplier) => needed.has(supplier.id));
      const output: SuppliersOutput = { kind: "suppliers", suppliers };

      return textResult(
        `Found ${suppliers.length} supplier record(s): ${suppliers
          .map((s) => `${s.id} (${s.status})`)
          .join(", ")}`,
        output as unknown as Record<string, unknown>,
      );
    },
  };

  const computeReorderQty: ToolDefinition<typeof runtimeArgs> = {
    name: "compute_reorder_qty",
    description:
      "Computes order-up-to quantities for low-stock SKUs from demand, lead time, review period and safety stock, rounded up to case packs. Consumes check_inventory output.",
    capability: "compute",
    produces: "reorder",
    consumes: ["inventory"],
    schema: runtimeArgs,
    handler: ({ upstream }) => {
      const inventory = findUpstream<InventoryOutput>(upstream, "inventory");
      if (!inventory) return missingUpstream("compute_reorder_qty", "inventory", "check_inventory");

      const lines = computeReorderLines(inventory.lowStock, inventory.reviewPeriodDays);
      const totalValueUsd = Math.round(lines.reduce((sum, l) => sum + l.lineValueUsd, 0) * 100) / 100;
      const output: ReorderOutput = {
        kind: "reorder",
        reviewPeriodDays: inventory.reviewPeriodDays,
        lines,
        totalValueUsd,
      };

      return textResult(
        `${lines.length} order line(s), ${usd(totalValueUsd)} total: ${lines
          .map((l) => `${l.sku} x${l.qty}`)
          .join(", ")}`,
        output as unknown as Record<string, unknown>,
      );
    },
  };

  const checkCompliance: ToolDefinition<typeof runtimeArgs> = {
    name: "validate_compliance",
    description:
      "Validates proposed order lines against distribution rules: supplier on hold, HAZMAT and cold-chain certification, and the auto-approval value limit. Consumes compute_reorder_qty output; uses lookup_suppliers output when a task provides it.",
    capability: "compute",
    produces: "compliance",
    consumes: ["reorder"],
    schema: runtimeArgs,
    handler: ({ upstream }) => {
      const reorder = findUpstream<ReorderOutput>(upstream, "reorder");
      if (!reorder) return missingUpstream("validate_compliance", "reorder", "compute_reorder_qty");

      const warehouse = load();
      const fromUpstream = findUpstream<SuppliersOutput>(upstream, "suppliers");
      const result = validateCompliance(
        reorder.lines,
        fromUpstream?.suppliers ?? warehouse.suppliers,
        warehouse.approvalThresholdUsd,
      );
      const output: ComplianceOutput = {
        kind: "compliance",
        ...result,
        supplierSource: fromUpstream ? "upstream" : "master data",
      };

      return textResult(
        `${result.approved.length} line(s) approved (${usd(result.approvedValueUsd)}), ` +
          `${result.breaches.length} breach(es)${
            result.breaches.length > 0
              ? `: ${result.breaches.map((b) => `${b.sku} ${b.rule}`).join(", ")}`
              : ""
          }`,
        output as unknown as Record<string, unknown>,
      );
    },
  };

  const notifySupplier: ToolDefinition<typeof runtimeArgs> = {
    name: "notify_supplier",
    description:
      "Sends one purchase order per supplier for the compliance-approved lines, via each supplier's ordering portal. Consumes validate_compliance output.",
    capability: "publish",
    produces: "notification",
    consumes: ["compliance"],
    schema: runtimeArgs,
    handler: ({ upstream, runId }) => {
      const compliance = findUpstream<ComplianceOutput>(upstream, "compliance");
      if (!compliance) return missingUpstream("notify_supplier", "compliance", "validate_compliance");

      const warehouse = load();
      const suppliers = new Map(warehouse.suppliers.map((s) => [s.id, s]));
      const grouped = groupBySupplier(compliance.approved);

      // All-or-nothing: check every portal before sending anything, so a
      // failure never leaves half the orders sent and half not. A partial send
      // is the one outcome a replan cannot cleanly repair.
      const unreachable = [...grouped.keys()].filter(
        (id) => forcedDown.has(id) || suppliers.get(id)?.portal === "down",
      );
      if (unreachable.length > 0) {
        return errorResult(
          `Supplier portal unreachable for ${unreachable.join(", ")}; no purchase orders were sent`,
        );
      }

      const dir = runFolder(runId);
      const issuedAt = now();
      const orders: PurchaseOrder[] = [];

      for (const [supplierId, lines] of grouped) {
        const supplier = suppliers.get(supplierId);
        if (!supplier) continue;
        const file = join(dir, `PO-${supplierId}.md`);
        writeFileSync(file, renderPurchaseOrder(warehouse, supplier, lines, issuedAt), "utf8");
        orders.push({
          supplierId,
          supplierName: supplier.name,
          email: supplier.email,
          lines,
          valueUsd: Math.round(lines.reduce((sum, l) => sum + l.lineValueUsd, 0) * 100) / 100,
          file,
        });
      }

      const output: NotificationOutput = { kind: "notification", orders };
      return textResult(
        orders.length === 0
          ? "No approved lines, so no purchase orders were needed"
          : `Sent ${orders.length} purchase order(s): ${orders
              .map((o) => `${o.supplierId} ${usd(o.valueUsd)}`)
              .join(", ")}`,
        output as unknown as Record<string, unknown>,
      );
    },
  };

  const queueManualReview: ToolDefinition<typeof runtimeArgs> = {
    name: "queue_manual_review",
    description:
      "Queues approved order lines and any compliance breaches for a buyer to place manually. Use when purchase orders cannot be sent automatically. Consumes validate_compliance output.",
    capability: "publish",
    produces: "manual_review",
    consumes: ["compliance"],
    schema: runtimeArgs,
    handler: ({ upstream, runId }) => {
      const compliance = findUpstream<ComplianceOutput>(upstream, "compliance");
      if (!compliance) return missingUpstream("queue_manual_review", "compliance", "validate_compliance");

      const file = join(runFolder(runId), "manual-review.md");
      const reason = "Automatic purchase orders could not be sent; a buyer must place these.";
      writeFileSync(
        file,
        [
          "# Manual review queue",
          "",
          reason,
          "",
          "## Lines to place",
          "",
          "| SKU | Supplier | Qty | Line value |",
          "|---|---|---:|---:|",
          ...compliance.approved.map(
            (l) => `| ${l.sku} | ${l.supplierId} | ${l.qty} | ${usd(l.lineValueUsd)} |`,
          ),
          "",
          "## Compliance breaches",
          "",
          ...(compliance.breaches.length === 0
            ? ["None."]
            : compliance.breaches.map((b) => `- **${b.sku}** (${b.supplierId}): ${b.detail}`)),
          "",
        ].join("\n"),
        "utf8",
      );

      const output: ManualReviewOutput = {
        kind: "manual_review",
        file,
        lines: compliance.approved,
        breaches: compliance.breaches,
        reason,
      };
      return textResult(
        `Queued ${compliance.approved.length} line(s) and ${compliance.breaches.length} breach(es) for manual review`,
        output as unknown as Record<string, unknown>,
      );
    },
  };

  return [checkInventory, lookupSuppliers, computeReorderQty, checkCompliance, notifySupplier, queueManualReview];
}

export const SUPPLY_CHAIN_TOOL_NAMES = [
  "check_inventory",
  "lookup_suppliers",
  "compute_reorder_qty",
  "validate_compliance",
  "notify_supplier",
  "queue_manual_review",
] as const;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SUPPLY_CHAIN_TOOLS: ToolDefinition<any>[] = makeSupplyChainTools();
